favicon: "/images/favicon.ico"
avatar: "/images/avatar.jpg"

menu:
  Home: /
  # Archives: /archives
  About: /about

copyright: All Rights Reserved.

gitalk:
  client_id: 4922669aa03c351fe839
  client_secret: bf07adc236fe2e657ff9d6b3967cfea4a1ac4ef7
  repo: https://github.com/starit/starit-me-comments
  owner: starit
